creation_rules:
  - path_regex: environments/asia/secrets(/)?.*\.yaml(.dec)?$
    gcp_kms: projects/helix-dev-polygon/locations/global/keyRings/polygon-dev/cryptoKeys/polygon
  - path_regex: environments/eu/secrets(/)?.*\.yaml(.dec)?$
    gcp_kms: projects/helix-dev-polygon/locations/global/keyRings/polygon-dev/cryptoKeys/polygon
  - path_regex: environments/us/secrets(/)?.*\.yaml(.dec)?$
    gcp_kms: projects/helix-dev-polygon/locations/global/keyRings/polygon-dev/cryptoKeys/polygon