amqp_url = "amqp://{{.Values.auth.username}}:{{.Values.auth.password}}@polyrabbitmq:5672/"
bor_rpc_url = "http://bor:8545"
checkpoint_poll_interval = "5m0s"
clerk_poll_interval = "10s"
eth_rpc_url = "{{ .Values.heimdall_cm.eth_rpc_url }}"
heimdall_rest_server = "http://0.0.0.0:1317"
main_chain_gas_limit = "5000000"
no_ack_wait_time = "30m0s"
noack_poll_interval = "16m50s"
span_poll_interval = "1m0s"
syncer_poll_interval = "1m0s"
tendermint_rpc_url = "http://0.0.0.0:26657"
