apiVersion: v1
kind: Secret
metadata:
  name: {{ template "heimdall.fullname" . }}-secret
  labels:
    app: {{ template "heimdall.name" . }}
    chart: {{ template "heimdall.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  heimdall-config.toml: |-
  {{- include (print $.Template.BasePath "/_heimdall-config.toml") . | nindent 4 }}
---
