apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "rabbitmq.fullname" . }}
provisioner: {{ .Values.persistence.provisioner }}
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
