{{ if .Values.ingress.enabled }}
{{- $fullName := include "bor.fullname" . -}}
{{- $svcProxyPort := ternary .Values.proxy.ws.port .Values.ws.port .Values.proxy.enabled -}}
{{- $svcPort := .Values.ws.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.org/websocket-services: {{ template "bor.fullname" . }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certmanagerClusterIssuer }}
  labels:
    app: {{ template "bor.name" . }}
    chart: {{ template "bor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "bor.fullname" . }}-bor-ws
spec:
  rules:
  {{- range .Values.ingress.ws.proxyHosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcProxyPort }}
        path: /
  {{- end }}
  {{- range .Values.ingress.ws.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
        path: /
  {{- end }}
  tls:
  - hosts:
    {{- range .Values.ingress.ws.proxyHosts }}
    - {{ . | quote }}
    {{- end }}
    {{- range .Values.ingress.ws.hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ $fullName }}-ws-tls
{{ end }}
