apiVersion: v1
kind: Service
metadata:
  name: {{ template "bor.fullname" . }}-monitoring
  labels:
    app: {{ template "bor.name" . }}
    chart: {{ template "bor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: monitoring
      port: 6060
      targetPort: monitoring
  selector:
    app: {{ template "bor.name" . }}
    release: {{ .Release.Name }}
