apiVersion: v1
kind: Service
metadata:
  name: {{ template "bor.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "bor.name" . }}
    chart: {{ template "bor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalLBp2pIP }}
  loadBalancerIP: {{ .Values.service.externalLBp2pIP }}
  {{- end }}
  ports:
    - name: httprpc
      port: {{ .Values.httpRPC.port }}
      targetPort: http-rpc
    - name: ws-rpc
      port: {{ .Values.wsRPC.port }}
      targetPort: ws-rpc
  selector:
    app: {{ template "bor.name" . }}
    release: {{ .Release.Name }}
